language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source

script:
  - ./vendor/codeception/bin/codeception run unit --xml

matrix:
  allow_failures:
    - php: hhvm